spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.24.137.206:33070/reader?useUnicode=true&charsetEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql147

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
      continue-on-error: true